# Usa una imagen base con Java 17
FROM adoptopenjdk:17-jdk-hotspot

# Copia el archivo JAR de tu aplicación al contenedor
COPY target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

# Establece el directorio de trabajo en /app
WORKDIR /app

# Expone el puerto 8080 en el contenedor
EXPOSE 8080

# Comando para ejecutar la aplicación Spring Boot
CMD ["java", "-jar", "demo.jar"]
